### ISSUE TITLE
Enable the user to generate an empty Plotly.js React component optionally

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#48]
We want to be able to create custom visualizations using [Plotly.js](https://plotly.com/javascript/). There already is an explanation of how to integrate it into a React component. 

Add a new function (command line switch `-plotlyReact` or command line argument `genPlotlyReactTemplate`) that needs to be called explicitly and generates a fully functional plotly.js react component in which the user can start plotting away. Inside the component make the so called `request` modules available, so that the plotter can get easy access to data that shall be visualized. This function shall not become part of the default generated code. The user must explicitly invoke the new command to get a plotly.js react component for the current data model.

**Comment by framirez07** [comment]
Already [implemented](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.5).
