### ISSUE TITLE
Mark identifiers in the detail and table view

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#51]
See [@coeit's  request](https://scidb-conabio.slack.com/archives/CE5BRGBLZ/p1589818274021600).

Please mark a data model's identifier (internal or default) in the detail view as being the ID. Put the ID always on top in the detail view and put a little "key" symbol next to it. On mouse over the key symbol the internationalized text appears "Unique Identifier".

Make the ID the first attribute (field) in the table and also add the little key symbol as above.

If you find a better way, e.g. how material design does that, use their standard.

**Comment by framirez07** [comment]
Already [implemented](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.5).
