### ISSUE TITLE
Tabular "master" view does not seem to be respecting record limit

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#54]
Using `latest-stable` of the code-generators and the skeleton single-page-application projects the created SPA causes the following error:

```
Error details:
[
     {
          "message": "transcript_countsConnection could not be fetched.",
          "locations": [
               {
                    "model": "transcript_count",
                    "query": "transcript_countsConnection",
                    "method": "getData()",
                    "request": "api.transcript_count.getItemsConnection"
               }
          ],
          "path": [
               "Transcript_counts"
          ],
          "extensions": {
               "graphqlResponse": {
                    "data": {
                         "transcript_countsConnection": null
                    },
                    "errors": [
                         {
                              "message": "Max record limit of 10000 exceeded in transcript_countsConnection",
                              "locations": [
                                   {
                                        "line": 2,
                                        "column": 13
                                   }
                              ],
                              "path": [
                                   "transcript_countsConnection"
                              ]
                         }
                    ]
               }
          }
     }
]
```

All data models that have more than 10,000 rows cause a similar error.

Fix the bug, write an integration test that first reproduces the error and than ensures it is fixed. Make sure the error does not appear in the limit-offset-based pagination either.

**Comment by asishallab** [comment]
## Correction: Bug is in GraphQL server not in the SPA

The generated function `checkCountAndReduceRecordLimit` does not take into account the pagination argument. This is a design flaw that causes the bug to occur always, if more records exists than the record limit allows to be fetches in a single query. 

## Fix

Make the function receive the `pagination` argument as well and adjust the record limit accordingly.

**Comment by framirez07** [comment]
Already [fixed](https://github.com/Zendro-dev/graphql-server-model-codegen/commit/f36cabc2f8c6d57f2735b6acccd80f83ab1aea99).
