### ISSUE TITLE
Improve password handling of Users in the Admin section of the SPA

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#55]
Currently the password are shown as hashed values. These are not informative and should _not_ be displayed, neither in the table view, nor in the detail view. 

Upon creating a new or updating an existing user the administrator must be able to set or change the password respectively.

**Comment by framirez07** [comment]
Already [implemented](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.3).
