### ISSUE TITLE
Use the same method to authorize user access to certain actions (permission) on resources in the SPA as is used in the GraphQL server

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#57]
In the backend GraphQL server we use access control lists which are kept in memory to be efficient. 

The respective resources implementing this authorization check are:
* [graphql-server/acl_rules.js](https://github.com/Zendro-dev/graphql-server/blob/master/acl_rules.js)
* [graphql-server/utils/check-authorization.js](https://github.com/Zendro-dev/graphql-server/blob/master/utils/check-authorization.js)

Basically, the backend GraphQL resolvers have four basic actions (permissions) that are checked for each respective data model (resource). These are the standard CRUD functions: create, read, update, and delete. The data model names are identical to the definitions, the input to the code-generators. 

Use these checks to restrict or cede access to the respective SPA components.

### Implementation for the SPA

Because the SPA code-generators already create the required `acl_rules.js` file, we most likely only need to adjust he roles in that file. In contrast to the original job description we realized that because there are several roles per data model, this file and authorization handling becomes quickly tedious. Revert to expecting three basic roles:
* read access is provided to guests on all data models, except user, role, and role_to_use
* all write functions, i.e. create, update, and delete, is made available to the role scientist on all data models
* only the administrator has CRUD access to the models user, role, and role_to_user. Thus only admins have access to the "admin" part of the main menu.

### Change the name of the three default roles

* guest becomes reader
* scientist becomes editor
* administrator remains administrator

**Comment by framirez07** [comment]
Already [implemented](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.5).
