### ISSUE TITLE
Improve icons used to show no-content (NULL) vs content (not NULL) values 

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#58]
Currently the SPA shows non null (non empty set) values with little check marks. This is misleading, because typically this suggests valid values, even though provided values can be invalid.

Use the existence and non existence quantifier from predicate logic (inverted capital E and crossed out inverted capital E). Check if you can make material icons yourself. For example using [this online tool](https://materialdesignicons.com/custom).

If creating custom icons is too much work or too tedious (work-time over 3 hours) please use a happy smiley face for existing and a non happy for non existing (null) values.

**Comment by framirez07** [comment]
Already [implemented](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.5).
