### ISSUE TITLE
ingle-page-app-codegen/pull/71 causing ejs error

### ISSUE THREAD

**Issue by coeit** [Zendro-dev/single-page-app-codegen#73]
## Issue
Have a look at the following comment in [pr71](https://github.com/Zendro-dev/single-page-app-codegen/pull/71)

https://github.com/Zendro-dev/single-page-app-codegen/pull/71#issuecomment-726208708

**Comment by framirez07** [comment]
Fixed in this: [commit](https://github.com/Zendro-dev/single-page-app-codegen/commit/8c100714e872f8ef4327fd32656ca0569827c6dd)
