### ISSUE TITLE
Download of example table causes an error

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#84]
This bug has been found using the current Zendro version (time of writing).

In the example table view of data model "Material" (data model definitions attached as txt so GitHub accepts the file-type)
when clicking on "download options" and "Download table-template to CSV" an error occurs (see attached screenshot). 

Unfortunately no error appears in the graphql-server or spa logs. The error in the console does not offer more information either.

Finally, note the green "template downloaded successfully" message, which obviously is wrong.

Please fix the bug and change the name of "Download table-template to CSV" to "Example table for bulk upload" or something more meaningful.

![zendro-spa-download-template-error](https://user-images.githubusercontent.com/575529/106909043-29919600-6700-11eb-872e-5a2a1490d550.png)

Data-Model definitions:
* [fileAttachment.txt](https://github.com/Zendro-dev/single-page-app-codegen/files/5926480/fileAttachment.txt)
* [material.txt](https://github.com/Zendro-dev/single-page-app-codegen/files/5926481/material.txt)
* [ontologyAnnotation.txt](https://github.com/Zendro-dev/single-page-app-codegen/files/5926482/ontologyAnnotation.txt)

**Comment by coeit** [comment]
fixed in b514d9895974efad58d1c208badb8b4830f173b3 (single-page-app-codegen) and [6c29154](https://github.com/Zendro-dev/single-page-app/commit/6c29154afdfd061ed1f2ca2e9fabadfbb9968bac)(single-page-app)
